btb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('cart.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path, include
from . import views
from django.views.decorators.cache import cache_page

app_name = 'btb'

urlpatterns = [

    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.contact_success, name="contact-success"),
    path('price/', views.CarsView.as_view(), name="cars"),


]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
 <meta name="theme-color" content="#FFA500">

 {% block css %}

 {% endblock %}
    
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.10.0-web/css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.10.0-web/css/fontawesome.css' %}" />
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.10.0-web/webfonts' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'font/flaticon.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'font/flaticon.woff' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'font/flaticon.woff2' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'font/flaticon.eot' %}" />
</head>

<body>


    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% include "navbar.html" %}

{% block content %}


{% endblock content %}



</body>

</html>

templates/contact-success.html
{% extends 'base.html' %}

 {% block css %}
<title>Contact Us</title>

 {% endblock %}
{% load static %}
{% block content %}


<section class="contact_hero">

    <div class="container">
        <div class="desc">
            <h1>Thank you for <br> your mail</h1>
        
        </div>
        <div class="image">
            <img src="{% static 'images/contact.svg' %}" alt="">
       
        </div>
    </div>
</section>

<main>

    
</main>





{% endblock content %}

templates/contact.html
{% extends 'base.html' %}

 {% block css %}
<title>Contact Us - BTB</title>

 {% endblock %}
{% load static %}
{% block content %}


<section class="contact_hero">

    <div class="container">
        <div class="desc">
            <h1>Reach out to us</h1>
        
        </div>
        <div class="image">
            <img src="{% static 'images/contact.svg' %}" alt="">
       
        </div>
    </div>
</section>

<main>

    <section class="contact_section">

        <div class="container">

<div class="office_section">
    <div class="container">
        <div class="office_box">

            <div class="icon"><img src="{% static 'images/icon.svg' %}" alt=""></div>
            <div class="office_text">
                <h3>OFFICE</h3>
                <h1>5678  Seltice Way Coeur D Alene, ID 12345</h1>
                <p>Sed fringilla mauris sit amet nibh.
                    Donec sodales sagittis</p>
            </div>
        </div>
        <div class="office_box">

            <div class="icon"><img src="{% static 'images/icon.svg' %}" alt=""></div>
            <div class="office_text">
                <h3>OFFICE</h3>
                <h1>5678  Seltice Way Coeur D Alene, ID 12345</h1>
                <p>Sed fringilla mauris sit amet nibh.
                    Donec sodales sagittis</p>
            </div>
        </div>
    </div>
</div>

            <div class="form-section">

                <div class="title"><h1> <span class="orange">Get in touch</span> with <br> our support team</h1>
                <p>We’d love to hear from you.</p></div>

                <div class="form_container">
                   <form class="form" method="post">
                       
{% csrf_token %}

                    <label>
                        <h1>Name:</h1>
                  {{form.name}}


                    </label>
                    
                    <label>
                        <h1>Email:</h1>
                        {{form.email}}



                    </label>
                    
                    <label>
                        <h1>Phone:</h1>
                        {{form.phone}}

                    </label>
                           
                    <label>
                        <h1>Message:</h1>
                        {{form.message}}

                    </label>

                    <button type="submit" class="btn btn-home">Send Message</button>
                   </form>
                </div>
            </div>
        </div>
    </section>
    
</main>





{% endblock content %}

templates/footer.html
<footer>

    <div class="container">

        <ul class="footer-container">
            <li class="footer_link">

                <a href="#">Term of Play</a>
            </li>
            <li class="footer_link">

                <a href="#">Term of Play</a>
            </li>
            <li class="footer_link">

                <a href="#">Term of Play</a>
            </li>
            <li class="footer_link">

                <a href="#">Term of Play</a>
            </li>
        </ul>
    </div>
</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<title>Home - BTB</title>

{% endblock css %}
{% block content %}



<main>

    <section class="hero">
        <div class="container">
            <h1>Win Your Dream Car</h1>
            <a href="{% url 'btb:cars' %}" class="btn btn-home">Enter Now</a>

        </div>
    </section>

    <section class="works">

        <div class="container">

            <div class="title">


                <h1>How Does It Work</h1>
            </div>

            <div class="work_cover">

                <div class="works_box">

                    <img src="{% static 'images/logo.svg' %}" alt="">
                    <h1>Tickets from 15p</h1>
                    <p>150 Cars
                        & 200 Lifestyle prizes to win</p>
                </div>
                <div class="works_box">

                    <img src="{% static 'images/logo.svg' %}" alt="">
                    <h1>Tickets from 15p</h1>
                    <p>150 Cars
                        & 200 Lifestyle prizes to win</p>
                </div>
                <div class="works_box">

                    <img src="{% static 'images/logo.svg' %}" alt="">
                    <h1>Tickets from 15p</h1>
                    <p>150 Cars
                        & 200 Lifestyle prizes to win</p>
                </div>
            </div>

            <div class="work_button">
                <a href="{% url 'btb:cars' %}" class="btn btn-home">Enter Now</a>
            </div>
        </div>
    </section>

    <!-- <section class="winners">

        <div class="container">

            <div class="title">
                <h1>Weekly Winners</h1>
            </div>

            <div class="winner_cover">

                <div class="winner_box">

                    <img src="{% static 'images/dc3320-kfi.jpg' %}" alt="">

                    <h1>Andrew Boyle</h1>
                    <h3>Tesla Model 3 Standard Range + £20k</h3>
                    <p>Winner #541 - (17 - 23 Aug 2020)</p>
                </div>
                <div class="winner_box">

                    <img src="{% static 'images/dc3320-kfi.jpg' %}" alt="">

                    <h1>Andrew Boyle</h1>
                    <h3>Tesla Model 3 Standard Range + £20k</h3>
                    <p>Winner #541 - (17 - 23 Aug 2020)</p>
                </div>
                <div class="winner_box">

                    <img src="{% static 'images/dc3320-kfi.jpg' %}" alt="">

                    <h1>Andrew Boyle</h1>
                    <h3>Tesla Model 3 Standard Range + £20k</h3>
                    <p>Winner #541 - (17 - 23 Aug 2020)</p>
                </div>
            </div>
        </div>
    </section> -->

    <section class="what_say">
        <div class="container">
            <div class="say_image">
                <img src="{% static 'images/about.png' %}" alt="">
            </div>
            <div class="say_text">
                <h3>ATHENA UI KIT TEMPLATE</h3>
                <h1>What They Say
                    About Us?</h1>
                <p>The best years of your life are the ones in which you decide your problems are your own. You do not
                    blame them on your mother, the ecology, or the president. You realize that you control your own
                    destiny.</p>
                <a href="#" class="btn btn-home">Learn More</a>
            </div>
        </div>
    </section>
    <section class="what_say">
        <div class="container">
      
            <div class="say_text">
                <h3>ATHENA UI KIT TEMPLATE</h3>
                <h1>What They Say
                    About Us?</h1>
                <p>The best years of your life are the ones in which you decide your problems are your own. You do not
                    blame them on your mother, the ecology, or the president. You realize that you control your own
                    destiny.</p>
                <a href="#" class="btn btn-home">Learn More</a>
            </div>

            <div class="say_image">
                <img src="{% static 'images/about.png' %}" alt="">
            </div>
        </div>
    </section>
</main>





{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}
{% load static %}


<nav class="main_nav">
<div class="container">

    <div class="logo"><a href="{% url 'btb:home' %}"><img src="{% static 'images/logo.svg' %}" alt=""></a></div>
    <div class="nav_items">

        <ul class="nav_links">
            <li><a href="#">Competition</a></li>
            <li><a href="#">Winners</a></li>
            <li><a href="#">About</a></li>
        </ul>
    </div>
    <div class="signup">
        <!-- &#8358; -->
        <ul>
           {% if request.user.is_authenticated %}
             <li><a href="#"> {{request.user|cart_item_price}}
                <i class="fas fa-shopping-cart"></i></a></li>
                   <li><a href="{% url 'account_logout' %}">Logout
                    <i class="fas fa-sign-out-alt"></i></a></li>

           {%else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li class="btn btn-home"><a href="{% url 'account_signup' %}">Sign Up</a></li>
          
           {% endif %}
        </ul>
    </div>
</div>

    </nav>

templates/price.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block css %}
<title>Cars - BTB</title>
{% endblock %}


{% block content %}

<section class="price_hero">

    <div class="container">





    </div>
</section>


<section class="car_price">

    <div class="car_row">
{% for item in cars %}
        <div class="car_col">

            <div class="quantity">
                <ul>

                    <li><a href="{{item.get_add_one}}">1</a></li>
                    <li><a href="{{item.get_add_five}}">5</a></li>
                    <li><a href="{{item.get_add_ten}}">10</a></li>
                    <li><a href="{{item.get_add_twenty}}">20</a></li>
                    <li><a href="{{item.get_add_fifty}}">50</a></li>
                    <li><a href=""><i class="fas fa-plus"></i></a></li>
                </ul>
            </div>

            <h1>{{item.title|title}} </h1>
            <p>Urus</p>
            <img src="{{item.image.url}}" alt="{{item.title|title}} ">
            <div class="price_alt"> &#8358; {{item.price|intcomma}} </div>
        </div>
{% endfor %}
    </div>
</section>


{% endblock content %}